Device websocket changes
jacktrip/jacktrip-agent pull request #7
Opened 2021-08-27 19:00 UTC by arctan5x

- Device -> Audio Server ping uses a socket over a 5 second period to measure RTT.
- Device <-> API Server uses tcp socket when a device is connected to an audio server. Otherwise, back to old ping/config exchange. This allows only "connected" devices establish a socket so we don't overload NATs.

2021-08-31 00:34 UTC, mikedickey requested changes

2021-08-31 00:34 UTC, mikedickey commented on cmd/services.go
> -			panic(err)
i'm not sure it's a good idea to ignore service start failures. currently, this causes the agent to exit and get restarted by systemd, which allows it to keep retrying to recover from any failures.

2021-08-31 00:34 UTC, mikedickey commented on cmd/deviceWSConnector.go
> +var ReceivePingChannel chan bool
similar to devicePinger, i think we can (and should) eliminate the singletons by moving the variables & methods into the `webSocketConnector` struct.

2021-08-31 00:34 UTC, mikedickey commented on cmd/deviceWSConnector.go
> +	Connector.Conn.SetWriteDeadline(time.Now().Add(3 * time.Second))
I think it's risky that you can have multiple threads/routines using this socket at the same time. I recommend having a single goroutine running inside this class that handles all send and receive operations, and uses channels to communicate with other threads.

2021-08-31 18:06 UTC, arctan5x commented on cmd/services.go
> +	log.Info(fmt.Sprintf("Starting managed service %s", name))
it always has to be a pair.

2021-08-31 23:12 UTC, arctan5x commented
@mikedickey I tried with timing out the read channel and use a case to write if there is any pending message. Gorilla websocket's setReadTimeout actually marks the connection corrupt when it times out, so we cannot use it in the loop since our websocket will be unusable every iteration in the for loop. Instead, I made two handlers with your favorite read and write locks ;)

2021-08-31 23:18 UTC, nwang92 approved these changes

2021-09-02 00:44 UTC, nwang92 approved these changes

2021-09-08 17:02 UTC, mikedickey approved these changes

2021-09-08 17:02 UTC, merged